
name: CI/CD with Docker Deploy to Render

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. إعداد Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. تسجيل الدخول إلى Docker Hub (اختياري إذا تريد رفع الصورة)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. بناء صورة Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/btec-app:latest .

      # 5. رفع الصورة إلى Docker Hub (اختياري)
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/btec-app:latest

      # 6. نشر على Render باستخدام API
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{}' \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
``
